[profile.default]
src = "src"
out = "out"
libs = ["lib"]
viaIR = true

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "params_first"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
sort_imports = true
